package config

import (
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

type Config struct {
	Flake string `toml:"flake"`
	// Format selects the shape of modules generated by `nole analyse
	// --apply`: "module" (default), "flake-part", or "flake".
	Format string `toml:"format"`
	// Maintain holds defaults for `nole maintain`.
	Maintain MaintainConfig `toml:"maintain"`
}

type MaintainConfig struct {
	// Clean makes `nole maintain` also garbage-collect old generations and
	// optimise the store afterwards, equivalent to always passing --clean.
	// Can still be overridden per-invocation with --clean/--no-clean.
	Clean bool `toml:"clean"`
}

const defaultFormat = "module"

func Load() (*Config, error) {
	cfg := &Config{Format: defaultFormat}
	for _, path := range configPaths() {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			continue
		}
		if _, err := toml.DecodeFile(path, cfg); err != nil {
			return nil, err
		}
		if cfg.Format == "" {
			cfg.Format = defaultFormat
		}
		return cfg, nil
	}
	return cfg, nil
}

// configPaths returns candidate config file locations in priority order.
// User config takes precedence over system config.
func configPaths() []string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return []string{
			filepath.Join(xdg, "nole", "config.toml"),
			"/etc/nole/config.toml",
		}
	}
	home, _ := os.UserHomeDir()
	return []string{
		filepath.Join(home, ".config", "nole", "config.toml"),
		"/etc/nole/config.toml",
	}
}
